# Generated by Django 5.1.2 on 2025-12-06 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_category_offerinfo_category_productinfo_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerinfo',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
