# Generated by Django 5.1.2 on 2025-12-06 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_offerinfo_price_alter_productinfo_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerinfo',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
